In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df["cough"].unique()

<StringArray>
['Mild', 'Strong']
Length: 2, dtype: str

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.shape

(100, 6)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop(columns=["has_covid"])
y = df["has_covid"]

In [9]:
X.head()

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai

In [10]:
y.head()

0     No
1    Yes
2     No
3     No
4     No
Name: has_covid, dtype: str

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)

In [12]:
X_train.shape

(80, 5)

In [13]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [14]:
X_test.shape

(20, 5)

In [15]:
y_train

55    Yes
88     No
26    Yes
42    Yes
69     No
     ...
60    Yes
71     No
14     No
92     No
51    Yes
Name: has_covid, Length: 80, dtype: str

In [16]:
y_test

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: str